Anslagstavlan/Pages/CreateChatRoom.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Anslagstavlan.Models;
using Anslagstavlan.Database;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace Anslagstavlan.Pages
{
    public class CreateChatRoomModel : PageModel
    {
        private readonly AppDbContext database;
        private readonly IWebHostEnvironment webHostEnvironment;

        private ChatUserModel User { get; set; }
        
        [BindProperty]
        [Required]
        public ChatRoomModel ChatRoom { get; set; }

        [BindProperty]
        public IFormFile Image { get; set; }

        public CreateChatRoomModel(AppDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            database = context;
            this.webHostEnvironment = webHostEnvironment;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPost(int id)
        {
            User = database.Users.Where(user => user.ChatUserId == id).FirstOrDefault();
            
            if(Image != null)
            {
                string folder = Path.Combine(webHostEnvironment.WebRootPath, "imgs");

                if(!Directory.Exists(folder))
                {
                    Directory.CreateDirectory(folder);
                }

                string ext = Path.GetExtension(Image.FileName);
                
                string uniqueFileName = String.Concat(Guid.NewGuid().ToString(), "-", ChatRoom.ChatRoomName + ext);

                string uploadFolder = Path.Combine(folder, uniqueFileName);

                using (var fileStream = new FileStream(uploadFolder, FileMode.Create))
                {
                    Image.CopyTo(fileStream);
                }

                ChatRoom.Img = uniqueFileName;
            }

            ChatRoom.ChatRoomOwner = User.ChatUserId;
            ChatRoom.Messages = null;

            //Post ChatRoom to database
            database.Rooms.Add(ChatRoom);
            database.SaveChanges();
            
            return RedirectToPage("/Index", new { id = User.ChatUserId});
        }
    }
}

Anslagstavlan/Pages/DeleteChatRoom.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Anslagstavlan.Models;
using Anslagstavlan.Database;

namespace Anslagstavlan.Pages
{
    public class DeleteChatRoomModel : PageModel
    {
        private readonly AppDbContext database;

        public ChatUserModel CurrentUser { get; set; }
        public List<ChatRoomModel> Rooms { get; set; }

        public DeleteChatRoomModel(AppDbContext context)
        {
            database = context;
        }

        public void OnGet(int id)
        {
            CurrentUser = database.Users.Where(user => user.ChatUserId == id).FirstOrDefault();

            if (CurrentUser != null)
            {
                Rooms = database.Rooms.Where(room => room.ChatRoomOwner == CurrentUser.ChatUserId).ToList();
            }
        }

        public IActionResult OnPost(int id)
        {
            //Delete room from database
            ChatRoomModel room = database.Rooms.Where(room => room.ChatRoomId == id).FirstOrDefault();

            database.Remove(room);
            database.SaveChanges();

            return RedirectToPage("/Index", new { id = room.ChatRoomOwner});
        }
    }
}

Anslagstavlan/Pages/Edit1ChatRoom.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Anslagstavlan.Database;
using Anslagstavlan.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Anslagstavlan.Pages
{
    public class Edit1ChatRoomModel : PageModel
    {
        private readonly AppDbContext database;

        public ChatUserModel CurrentUser { get; set; }
        public List<ChatRoomModel> Rooms { get; set; }

        public Edit1ChatRoomModel(AppDbContext context)
        {
            database = context;
        }

        public void OnGet(int id)
        {
            CurrentUser = database.Users.Where(user => user.ChatUserId == id).FirstOrDefault();

            if (CurrentUser != null)
            {
                Rooms = database.Rooms.Where(room => room.ChatRoomOwner == CurrentUser.ChatUserId).ToList();
            }
        }

        public IActionResult OnPost(int id, int userId)
        {
            return RedirectToPage("Edit2ChatRoom", new { id = id, userId = userId});
        }
    }
}

Anslagstavlan/Pages/Edit2ChatRoom.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Anslagstavlan.Models;
using Anslagstavlan.Database;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace Anslagstavlan.Pages
{
    public class Edit2ChatRoomModel : PageModel
    {
        private readonly AppDbContext database;
        private readonly IWebHostEnvironment webHostEnvironment;

        [BindProperty]
        public ChatRoomModel Room { get; set; }

        [BindProperty]
        public IFormFile Image { get; set; }

        public Edit2ChatRoomModel(AppDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            database = context;
            this.webHostEnvironment = webHostEnvironment;
        }

        public void OnGet(int id, int userId)
        {
            Room = database.Rooms.Where(room => room.ChatRoomId == id).FirstOrDefault();
            Room.ChatRoomOwner = userId;
        }

        public IActionResult OnPostEdit()
        {
            if (Image != null)
            {
                string folder = Path.Combine(webHostEnvironment.WebRootPath, "imgs");

                if (!Directory.Exists(folder))
                {
                    Directory.CreateDirectory(folder);
                }

                string ext = Path.GetExtension(Image.FileName);

                string uniqueFileName = String.Concat(Guid.NewGuid().ToString(), "-", Room.ChatRoomName + ext);

                string uploadFolder = Path.Combine(folder, uniqueFileName);

                using (var fileStream = new FileStream(uploadFolder, FileMode.Create))
                {
                    Image.CopyTo(fileStream);
                }

                Room.Img = uniqueFileName;
            } 

            //Edit the room
            database.Update(Room);
            database.SaveChanges();

            int userId = Room.ChatRoomOwner;

            return RedirectToPage("Index", new { id = userId});
        }
    }
}

Anslagstavlan/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Anslagstavlan.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Anslagstavlan/Pages/Index.cshtml.cs
using Anslagstavlan.Database;
using Anslagstavlan.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Anslagstavlan.Pages
{
    public class IndexModel : PageModel
    {
        private readonly AppDbContext database;

        public ChatUserModel CurrentUser { get; set; }
        public List<ChatUserModel> CreatedRoomUsers { get; set; }
        public List<ChatRoomModel> Rooms { get; set; }

        public IndexModel(AppDbContext context)
        {
            database = context;
        }

        public void OnGet(int id)
        {
            CurrentUser = database.Users.Where(user => user.ChatUserId == id).FirstOrDefault();
            CreatedRoomUsers = new List<ChatUserModel>();

            if (CurrentUser != null)
            {
                //Change this so that all users can see all rooms created by all users
                Rooms = database.Rooms.ToList();

                foreach (var room in Rooms)
                {
                    ChatUserModel user = database.Users.Where(user => user.ChatUserId == room.ChatRoomOwner)
                        .FirstOrDefault();
                    CreatedRoomUsers.Add(user);
                }
            }
        }
    }
}

Anslagstavlan/Pages/LogIn.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Anslagstavlan.Models;
using Anslagstavlan.Database;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Anslagstavlan.Pages
{
    [BindProperties]
    public class LogInModel : PageModel
    {
        private readonly AppDbContext database;

        [Required]
        public ChatUserModel User { get; set; }

        public string Message { get; set; }

        public LogInModel(AppDbContext context)
        {
            database = context;
        }

        public void OnGet(string message)
        {
            Message = message;
        }

        public IActionResult OnPost()
        {

            if (ModelState.IsValid)
            {
                //Check if user is signed up 
                ChatUserModel signedUpUser = database.Users.Where(user => user.Username == User.Username).FirstOrDefault();

                if(signedUpUser != null)
                {
                    return RedirectToPage("/Index", new { id = signedUpUser.ChatUserId});
                }
            } 
            
            return RedirectToPage("/LogIn", new { message = "User not signed up, try again"});
        }
    }
}

Anslagstavlan/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Anslagstavlan.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Anslagstavlan/Pages/Room.cshtml.cs
using Anslagstavlan.Database;
using Anslagstavlan.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Anslagstavlan.Pages
{
    public class RoomModel : PageModel
    {
        public readonly AppDbContext database;

        public RoomModel(AppDbContext context)
        {
            database = context;
        }

        [BindProperty]
        public ChatRoomModel Room { get; set; }

        [BindProperty]
        public ChatMessageModel Message { get; set; }

        [BindProperty]
        public List<ChatUserModel> CreatedMessageUsers { get; set; }
        
        [BindProperty]
        public ChatUserModel CreatedRoomUser { get; set; }

        public void OnGet(int id)
        {
            Room = database.Rooms.Include(x => x.Messages).Where(room => room.ChatRoomId == id).FirstOrDefault();
            
            CreatedMessageUsers = new List<ChatUserModel>();
            CreatedRoomUser = new ChatUserModel();
            CreatedRoomUser = database.Users.Where(user => user.ChatUserId == Room.ChatRoomOwner)
                .FirstOrDefault();

            foreach (var message in Room.Messages)
            {
                ChatUserModel user = database.Users.Where(user => user.ChatUserId == message.ChatUserId)
                    .FirstOrDefault();
                CreatedMessageUsers.Add(user);
            }
        }

        public IActionResult OnPost(int userId)
        {
            Room = database.Rooms.Include(x => x.Messages).Where(room => room.ChatRoomId == Room.ChatRoomId).FirstOrDefault();

            ChatUserModel user = database.Users.Where(user => user.ChatUserId == userId).FirstOrDefault();

            Message.Date = DateTime.Now;
            Message.ChatRoom = Room;
            Message.ChatUser = user;

            database.Messages.Add(Message);
            database.SaveChanges();

            return RedirectToPage("Room", new { id = Room.ChatRoomId, userId = user.ChatUserId });
        }
    }
}

Anslagstavlan/Pages/SignUp.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Anslagstavlan.Models;
using Anslagstavlan.Database;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace Anslagstavlan.Pages
{
    public class SignUpModel : PageModel
    {
        private readonly AppDbContext database;
        private readonly IWebHostEnvironment webHostEnvironment;

        [Required]
        [BindProperty]
        public ChatUserModel User { get; set; }

        [BindProperty]
        public IFormFile Image { get; set; }

        public SignUpModel(AppDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            database = context;
            this.webHostEnvironment = webHostEnvironment;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            if (Image != null)
            {
                string folder = Path.Combine(webHostEnvironment.WebRootPath, "imgs");

                if (!Directory.Exists(folder))
                {
                    Directory.CreateDirectory(folder);
                }

                string ext = Path.GetExtension(Image.FileName);

                string uniqueFileName = String.Concat(Guid.NewGuid().ToString(), "-", User.Username + ext);

                string uploadFolder = Path.Combine(folder, uniqueFileName);

                using (var fileStream = new FileStream(uploadFolder, FileMode.Create))
                {
                    Image.CopyTo(fileStream);
                }

                User.Img = uniqueFileName;
            }

            if (ModelState.IsValid)
            {
                //Write user to database
                database.Users.Add(User);
                database.SaveChanges();
                database.Dispose();
            
            } else
            {
                return RedirectToPage("/Error");
            }

            return RedirectToPage("/Index", new { id = User.ChatUserId});
        }
    }
}

Anslagstavlan/Pages/CreateChatRoom.cshtml
@page
@model Anslagstavlan.Pages.CreateChatRoomModel
@{
}

<div class="text-center">
    <form method="post" enctype="multipart/form-data">
        <div class="mb-1">
            <label for="username">Chat room name:</label><br>
            <input required type="text" id="username" asp-for="@Model.ChatRoom.ChatRoomName">
        </div>
        <div class="mb-1">
            <label for="img">Upload image:</label> <br>
            <input type="file" id="img" asp-for="@Model.Image" />
        </div>
        <div class="mb-2">
            <input type="submit" />
        </div>
    </form>
</div>

Anslagstavlan/Pages/DeleteChatRoom.cshtml
@page
@model Anslagstavlan.Pages.DeleteChatRoomModel
@{
}

<div class="text-center">
    <h1>Select a room to delete</h1>
</div>

@if (Model.Rooms != null)
{
    @foreach (var room in Model.Rooms)
    {
        <div class="text-center">

            <form method="post">
                <p>
                    @room.ChatRoomName
                    <button class="btn btn-danger" asp-route-id="@room.ChatRoomId" asp-page-handler="Post">Delete</button>

                    @if (room.Img != null)
                    {
                        <img src="~/imgs/@room.Img" style="max-width:50px" />
                    }
                </p>
            </form>

        </div>
    }
}

Anslagstavlan/Pages/Edit1ChatRoom.cshtml
@page
@model Anslagstavlan.Pages.Edit1ChatRoomModel
@{
}

<div class="text-center">
    <h1>Select a room to edit</h1>
</div>

@if (Model.Rooms != null)
{
    @foreach (var room in Model.Rooms)
    {
        <div class="text-center">

            <form method="post">
                <p>
                    @room.ChatRoomName
                    <button class="btn btn-success" asp-route-id="@room.ChatRoomId" asp-route-userId="@room.ChatRoomOwner" 
                            asp-page-handler="Post">Edit</button>
                    @if (room.Img != null)
                    {
                        <img src="~/imgs/@room.Img" style="max-width:50px" />
                    }
                </p>
            </form>

        </div>
    }
}

Anslagstavlan/Pages/Edit2ChatRoom.cshtml
@page
@model Anslagstavlan.Pages.Edit2ChatRoomModel
@{
}

<div class="text-center">
    <h1 class="display-4">Edit room</h1>

    <form method="post" asp-page-handler="Edit" enctype="multipart/form-data">
        <input hidden asp-for="@Model.Room.ChatRoomId" />
        <input hidden asp-for="@Model.Room.ChatRoomOwner" />
        <input hidden asp-for="@Model.Room.Img" />
        <div class="mb-1">
            <label for="name">Name:</label><br>
            <input required type="text" id="name" asp-for="@Model.Room.ChatRoomName" placeholder="@Model.Room.ChatRoomName">
        </div>
        <div class="mb-1">
            <label for="img">Upload image:</label> <br>
            <input type="file" id="img" asp-for="@Model.Image" />
        </div>
        <div class="mb-2">
            <input type="submit" />
        </div>
    </form>

    @if (Model.Room.Img != null)
    {
        <div style="position:fixed;top:150px;right:200px">
            <img src="~/imgs/@Model.Room.Img" style="max-width:200px" />
        </div>
    }
</div>

Anslagstavlan/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-lg-right">
    @if (Model.CurrentUser != null)
    {
        <p style="color:dodgerblue">
            Logged in as "@Model.CurrentUser.Username"

            @if (Model.CurrentUser.Img != null)
            {
            <img src="~/imgs/@Model.CurrentUser.Img" style="max-width:50px" />
            }
        </p>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="btn btn-block" asp-page="/CreateChatRoom"
               asp-route-id="@Model.CurrentUser.ChatUserId">Create chat room</a>
            <a class="btn btn-block" asp-page="/DeleteChatRoom"
               asp-route-id="@Model.CurrentUser.ChatUserId">Delete chat room</a>
            <a class="btn btn-block" asp-page="/Edit1ChatRoom"
               asp-route-id="@Model.CurrentUser.ChatUserId">Edit chat room</a>
        </nav>
    }
    else
    {
        <p>Not logged in</p>
    }
</div>

<div class="text-center">
    <h1 class="display-4">Chat rooms: </h1>

    @if (Model.Rooms != null)
    {
        @foreach (var room in Model.Rooms)
        {
            @foreach (var user in Model.CreatedRoomUsers)
            {
                @if (user.ChatUserId == room.ChatRoomOwner)
                {
                    <p>
                        <a asp-page="/Room" asp-route-id="@room.ChatRoomId"
                           asp-route-userId="@Model.CurrentUser.ChatUserId">
                            @room.ChatRoomName
                        (created by "@user.Username"
                        @if (user.Img != null)
                        {
                            <img src="~/imgs/@user.Img" style="max-width:30px" />
                        }
                        )
                        </a>

                        @if (room.Img != null)
                        {
                            <img src="~/imgs/@room.Img" style="max-width:50px" />
                        }
                    </p>
                    break;
                }
            }
        }
    }

</div>

Anslagstavlan/Pages/LogIn.cshtml
@page
@model Anslagstavlan.Pages.LogInModel
@{
}

<div class="text-center">
    <h1>Log in to your account</h1>
</div>

<div class="text-lg-right">
    @if (!String.IsNullOrEmpty(Model.Message))
    {
        <p class="text-danger">@Model.Message</p>

    }
    else
    {
        
    }
</div>

<div class="text-center">
    <form method="post">
        <div class="mb-1">
            <label for="username">Username:</label><br>
            <input required type="text" id="username" asp-for="@Model.User.Username">
        </div>
        <div class="mb-2">
            <input type="submit" />
        </div>
    </form>
</div>

Anslagstavlan/Pages/Room.cshtml
@page
@model Anslagstavlan.Pages.RoomModel
@{
}

<div class="text-center">
    <h1>@Model.Room.ChatRoomName (created by "@Model.CreatedRoomUser.Username")</h1>
    <p>Add a message to @Model.Room.ChatRoomName</p>

    <form method="post">
        <div class="mb-1">
            <label for="message">Message:</label><br>
            <input hidden asp-for="@Model.Room.ChatRoomId" />
            <input hidden asp-for="@Model.CreatedRoomUser" />
            <input required type="text" id="message" asp-for="@Model.Message.Message">
        </div>
        <div class="mb-2">
            <input type="submit" />
        </div>
    </form>

    @if (Model.Room.Messages != null)
    {
        @foreach (var message in Model.Room.Messages)
        {
            @foreach (var user in Model.CreatedMessageUsers)
            {
                @if (user.ChatUserId == message.ChatUserId)
                {
                    <p>
                        @message.Message (posted by "@user.Username"

                        @if (user.Img != null)
                        {
                            <img src="~/imgs/@user.Img" style="max-width:30px" />
                        }
                        
                        at @message.Date)
                    </p>
                    break;
                }
            }
        }
    }

    @if (Model.Room.Img != null)
    {
        <div style="position:fixed;top:150px;right:200px">
            <img src="~/imgs/@Model.Room.Img" style="max-width:200px" />
        </div>
    }

</div>

Anslagstavlan/Pages/SignUp.cshtml
@page
@model Anslagstavlan.Pages.SignUpModel
@{
}

<div class="text-center">
    <h1>Sign up account</h1>
</div>

<div class="text-center">
    <form method="post" enctype="multipart/form-data">
        <input hidden asp-for="@Model.Image"/>
        <div class="mb-1">
            <label for="username">Username:</label><br>
            <input required type="text" id="username" asp-for="@Model.User.Username">
        </div>
        <div class="mb-1">
            <label for="img">Upload image:</label> <br>
            <input type="file" id="img" asp-for="@Model.Image" />
        </div>
        <div class="mb-2">
            <input type="submit" />
        </div>
    </form>
</div>